import { describe, it, expect, beforeEach } from 'vitest';
import transactionsRoutes from './index.js';
import { buildApp, TEST_USER_ID, OTHER_USER_ID } from '../../test/helpers.js';
import { transaction, creditCard, installmentPlan, installment, person, transactionSplit } from '../../db/schema/index.js';

describe('transactions routes', () => {
  let app: any;
  let db: any;

  beforeEach(async () => {
    const harness = await buildApp(transactionsRoutes, '/api/v1/transactions');
    app = harness.app;
    db = harness.db;
  });

  it('creates a transaction mapping amount to amountCents', async () => {
    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/transactions',
      payload: {
        description: 'Supermercado',
        amount: 10050,
        type: 'EXPENSE',
        date: new Date().toISOString(),
        paymentMethod: 'PIX',
      },
    });

    expect(res.statusCode).toBe(201);
    const body = res.json();
    expect(body.description).toBe('Supermercado');
    expect(body.amount).toEqual({ cents: 10050, currency: 'BRL' });

    const rows = db.all(transaction);
    expect(rows).toHaveLength(1);
    expect(rows[0].amountCents).toBe(10050);
    expect(rows[0].userId).toBe(TEST_USER_ID);
    expect(rows[0]).not.toHaveProperty('amount');
  });

  it('rejects a create with an unknown category', async () => {
    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/transactions',
      payload: {
        description: 'Teste',
        amount: 100,
        type: 'EXPENSE',
        date: new Date().toISOString(),
        paymentMethod: 'CASH',
        categoryId: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
      },
    });

    expect(res.statusCode).toBe(400);
  });

  it('updates a transaction mapping amount and date', async () => {
    db.seed(transaction, [{
      id: '99999999-9999-4999-8999-999999999999',
      userId: TEST_USER_ID,
      description: 'Antiga',
      amountCents: 1000,
      type: 'EXPENSE',
      date: new Date(),
      paymentMethod: 'CASH',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const newDate = new Date('2025-01-01T00:00:00.000Z');

    const res = await app.inject({
      method: 'PATCH',
      url: '/api/v1/transactions/99999999-9999-4999-8999-999999999999',
      payload: { description: 'Nova', amount: 2500, date: newDate.toISOString() },
    });

    expect(res.statusCode).toBe(200);
    expect(res.json().amount).toEqual({ cents: 2500, currency: 'BRL' });

    const rows = db.all(transaction);
    expect(rows[0].amountCents).toBe(2500);
    expect(rows[0].description).toBe('Nova');
    expect(rows[0].date).toEqual(newDate);
    expect(rows[0]).not.toHaveProperty('amount');
  });

  it('returns 404 when getting a transaction owned by another user', async () => {
    db.seed(transaction, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
      userId: OTHER_USER_ID,
      description: 'Outra',
      amountCents: 1000,
      type: 'EXPENSE',
      date: new Date(),
      paymentMethod: 'CASH',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({ method: 'GET', url: '/api/v1/transactions/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' });
    expect(res.statusCode).toBe(404);
  });

  it('deletes a transaction', async () => {
    db.seed(transaction, [{
      id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
      userId: TEST_USER_ID,
      description: 'Remover',
      amountCents: 500,
      type: 'EXPENSE',
      date: new Date(),
      paymentMethod: 'PIX',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({ method: 'DELETE', url: '/api/v1/transactions/cccccccc-cccc-4ccc-8ccc-cccccccccccc' });
    expect(res.statusCode).toBe(200);
    expect(db.all(transaction)).toHaveLength(0);
  });

  it('rejects editing a transaction generated by an installment plan', async () => {
    db.seed(transaction, [{
      id: 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',
      userId: TEST_USER_ID,
      description: 'Pagamento parcela 1/10 - Notebook',
      amountCents: 25000,
      type: 'EXPENSE',
      date: new Date(),
      paymentMethod: 'BANK_TRANSFER',
      installmentPlanId: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'PATCH',
      url: '/api/v1/transactions/dddddddd-dddd-4ddd-8ddd-dddddddddddd',
      payload: { description: 'Alterado' },
    });

    expect(res.statusCode).toBe(409);
  });

  it('rejects an edit with an account not owned by the user', async () => {
    db.seed(transaction, [{
      id: 'ffffffff-ffff-4fff-8fff-ffffffffffff',
      userId: TEST_USER_ID,
      description: 'Sem conta',
      amountCents: 1000,
      type: 'EXPENSE',
      date: new Date(),
      paymentMethod: 'CASH',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'PATCH',
      url: '/api/v1/transactions/ffffffff-ffff-4fff-8fff-ffffffffffff',
      payload: { accountId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' },
    });

    expect(res.statusCode).toBe(400);
  });

  it('creates an installment plan when installmentsCount is provided', async () => {
    db.seed(creditCard, [{
      id: '11111111-1111-4111-8111-111111111111',
      userId: TEST_USER_ID,
      name: 'Visa',
      institution: 'Banco',
      brand: 'VISA',
      last4: '1234',
      limitCents: 100000,
      availableLimitCents: 100000,
      closingDay: 5,
      dueDay: 10,
      status: 'ACTIVE',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/transactions',
      payload: {
        description: 'Notebook',
        amount: 30000,
        type: 'EXPENSE',
        date: new Date().toISOString(),
        paymentMethod: 'CREDIT_CARD',
        cardId: '11111111-1111-4111-8111-111111111111',
        installmentsCount: 3,
      },
    });

    expect(res.statusCode).toBe(201);
    expect(res.json().installments).toHaveLength(3);
    expect(db.all(transaction)).toHaveLength(0);
    expect(db.all(installmentPlan)).toHaveLength(1);
    expect(db.all(installment)).toHaveLength(3);
  });

  it('creates a transaction with people splits', async () => {
    db.seed(person, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaab',
      userId: TEST_USER_ID,
      name: 'Maria',
      type: 'INDIVIDUAL',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/transactions',
      payload: {
        description: 'Jantar',
        amount: 10000,
        type: 'EXPENSE',
        date: new Date().toISOString(),
        paymentMethod: 'PIX',
        splits: [{ personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaab', amountCents: 5000 }],
      },
    });

    expect(res.statusCode).toBe(201);
    expect(db.all(transactionSplit)).toHaveLength(1);
    expect(db.all(transactionSplit)[0].personId).toBe('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaab');
    expect(Number(db.all(transactionSplit)[0].amountCents)).toBe(5000);
  });

  it('rejects a transaction whose splits exceed the amount', async () => {
    db.seed(person, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaac',
      userId: TEST_USER_ID,
      name: 'João',
      type: 'INDIVIDUAL',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/transactions',
      payload: {
        description: 'Jantar',
        amount: 10000,
        type: 'EXPENSE',
        date: new Date().toISOString(),
        paymentMethod: 'PIX',
        splits: [{ personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaac', amountCents: 15000 }],
      },
    });

    expect(res.statusCode).toBe(400);
    expect(db.all(transactionSplit)).toHaveLength(0);
  });

  it('accepts splits whose sum equals the full amount', async () => {
    db.seed(person, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaad',
      userId: TEST_USER_ID,
      name: 'Ana',
      type: 'INDIVIDUAL',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/transactions',
      payload: {
        description: 'Jantar',
        amount: 10000,
        type: 'EXPENSE',
        date: new Date().toISOString(),
        paymentMethod: 'PIX',
        splits: [{ personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaad', amountCents: 10000 }],
      },
    });

    expect(res.statusCode).toBe(201);
    expect(db.all(transactionSplit)).toHaveLength(1);
  });

  it('creates splits for multiple people', async () => {
    db.seed(person, [
      { id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaae', userId: TEST_USER_ID, name: 'Ana', type: 'INDIVIDUAL', createdAt: new Date(), updatedAt: new Date() },
      { id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaf', userId: TEST_USER_ID, name: 'Bia', type: 'INDIVIDUAL', createdAt: new Date(), updatedAt: new Date() },
    ]);

    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/transactions',
      payload: {
        description: 'Churrasco',
        amount: 10000,
        type: 'EXPENSE',
        date: new Date().toISOString(),
        paymentMethod: 'PIX',
        splits: [
          { personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaae', amountCents: 5000 },
          { personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaf', amountCents: 2500 },
        ],
      },
    });

    expect(res.statusCode).toBe(201);
    expect(db.all(transactionSplit)).toHaveLength(2);
    const ids = db.all(transactionSplit).map((s: any) => s.personId).sort();
    expect(ids).toEqual([
      'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaae',
      'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaf',
    ]);
  });

  it('rejects a transaction with a duplicated person in splits', async () => {
    db.seed(person, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab0',
      userId: TEST_USER_ID,
      name: 'Carla',
      type: 'INDIVIDUAL',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/transactions',
      payload: {
        description: 'Jantar',
        amount: 10000,
        type: 'EXPENSE',
        date: new Date().toISOString(),
        paymentMethod: 'PIX',
        splits: [
          { personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab0', amountCents: 3000 },
          { personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab0', amountCents: 3000 },
        ],
      },
    });

    expect(res.statusCode).toBe(400);
    expect(db.all(transactionSplit)).toHaveLength(0);
  });

  it('rejects a split for a person owned by another user', async () => {
    db.seed(person, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab1',
      userId: OTHER_USER_ID,
      name: 'Forasteiro',
      type: 'INDIVIDUAL',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/transactions',
      payload: {
        description: 'Jantar',
        amount: 10000,
        type: 'EXPENSE',
        date: new Date().toISOString(),
        paymentMethod: 'PIX',
        splits: [{ personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab1', amountCents: 5000 }],
      },
    });

    expect(res.statusCode).toBe(400);
    expect(db.all(transactionSplit)).toHaveLength(0);
  });

  it('rejects a split with a non-positive amount', async () => {
    db.seed(person, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab2',
      userId: TEST_USER_ID,
      name: 'Dani',
      type: 'INDIVIDUAL',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/transactions',
      payload: {
        description: 'Jantar',
        amount: 10000,
        type: 'EXPENSE',
        date: new Date().toISOString(),
        paymentMethod: 'PIX',
        splits: [{ personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab2', amountCents: 0 }],
      },
    });

    expect(res.statusCode).toBe(400);
  });

  it('returns splits and splitTotal on the list', async () => {
    const txId = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab3';
    db.seed(transaction, [{
      id: txId,
      userId: TEST_USER_ID,
      description: 'Com splits',
      amountCents: 10000,
      type: 'EXPENSE',
      date: new Date(),
      paymentMethod: 'PIX',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);
    db.seed(person, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab4',
      userId: TEST_USER_ID,
      name: 'Eva',
      type: 'INDIVIDUAL',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);
    db.seed(transactionSplit, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab5',
      userId: TEST_USER_ID,
      transactionId: txId,
      personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab4',
      amountCents: BigInt(4000),
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({ method: 'GET', url: '/api/v1/transactions' });
    expect(res.statusCode).toBe(200);

    const body = res.json();
    expect(body.data).toHaveLength(1);
    expect(body.data[0].splits).toHaveLength(1);
    expect(body.data[0].splits[0].personId).toBe('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab4');
    expect(body.data[0].splits[0].amount).toEqual({ cents: 4000, currency: 'BRL' });
    expect(body.data[0].splits[0].person.name).toBe('Eva');
    expect(body.data[0].splitTotal).toEqual({ cents: 4000, currency: 'BRL' });
  });

  it('returns splits on a single transaction', async () => {
    const txId = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab6';
    db.seed(transaction, [{
      id: txId,
      userId: TEST_USER_ID,
      description: 'Com splits',
      amountCents: 10000,
      type: 'EXPENSE',
      date: new Date(),
      paymentMethod: 'PIX',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);
    db.seed(person, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab7',
      userId: TEST_USER_ID,
      name: 'Fabi',
      type: 'INDIVIDUAL',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);
    db.seed(transactionSplit, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab8',
      userId: TEST_USER_ID,
      transactionId: txId,
      personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab7',
      amountCents: BigInt(6000),
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({ method: 'GET', url: `/api/v1/transactions/${txId}` });
    expect(res.statusCode).toBe(200);

    const body = res.json();
    expect(body.splits).toHaveLength(1);
    expect(body.splits[0].amount).toEqual({ cents: 6000, currency: 'BRL' });
    expect(body.splits[0].person.name).toBe('Fabi');
    expect(body.splitTotal).toEqual({ cents: 6000, currency: 'BRL' });
  });

  it('replaces splits when patching a transaction', async () => {
    const txId = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaab9';
    db.seed(transaction, [{
      id: txId,
      userId: TEST_USER_ID,
      description: 'Antiga',
      amountCents: 10000,
      type: 'EXPENSE',
      date: new Date(),
      paymentMethod: 'PIX',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);
    db.seed(person, [
      { id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaac0', userId: TEST_USER_ID, name: 'Gabi', type: 'INDIVIDUAL', createdAt: new Date(), updatedAt: new Date() },
      { id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaac1', userId: TEST_USER_ID, name: 'Hugo', type: 'INDIVIDUAL', createdAt: new Date(), updatedAt: new Date() },
    ]);
    db.seed(transactionSplit, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaac2',
      userId: TEST_USER_ID,
      transactionId: txId,
      personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaac0',
      amountCents: BigInt(10000),
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'PATCH',
      url: `/api/v1/transactions/${txId}`,
      payload: {
        splits: [{ personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaac1', amountCents: 5000 }],
      },
    });

    expect(res.statusCode).toBe(200);
    const rows = db.all(transactionSplit);
    expect(rows).toHaveLength(1);
    expect(rows[0].personId).toBe('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaac1');
    expect(Number(rows[0].amountCents)).toBe(5000);
  });

  it('clears splits when patching with an empty list', async () => {
    const txId = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaac3';
    db.seed(transaction, [{
      id: txId,
      userId: TEST_USER_ID,
      description: 'Antiga',
      amountCents: 10000,
      type: 'EXPENSE',
      date: new Date(),
      paymentMethod: 'PIX',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);
    db.seed(person, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaac4',
      userId: TEST_USER_ID,
      name: 'Igor',
      type: 'INDIVIDUAL',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);
    db.seed(transactionSplit, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaac5',
      userId: TEST_USER_ID,
      transactionId: txId,
      personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaac4',
      amountCents: BigInt(5000),
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'PATCH',
      url: `/api/v1/transactions/${txId}`,
      payload: { splits: [] },
    });

    expect(res.statusCode).toBe(200);
    expect(db.all(transactionSplit)).toHaveLength(0);
  });

  it('rejects splits that exceed the patched amount', async () => {
    const txId = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaac6';
    db.seed(transaction, [{
      id: txId,
      userId: TEST_USER_ID,
      description: 'Antiga',
      amountCents: 10000,
      type: 'EXPENSE',
      date: new Date(),
      paymentMethod: 'PIX',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);
    db.seed(person, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaac7',
      userId: TEST_USER_ID,
      name: 'Jana',
      type: 'INDIVIDUAL',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'PATCH',
      url: `/api/v1/transactions/${txId}`,
      payload: {
        amount: 5000,
        splits: [{ personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaac7', amountCents: 6000 }],
      },
    });

    expect(res.statusCode).toBe(400);
    expect(db.all(transactionSplit)).toHaveLength(0);
  });
});