import { describe, it, expect, beforeEach } from 'vitest';
import transactionsRoutes from './index.js';
import { buildApp, TEST_USER_ID, OTHER_USER_ID } from '../../test/helpers.js';
import { transaction, creditCard, installmentPlan, installment, person, transactionSplit } from '../../db/schema/index.js';

describe('transactions routes', () => {
  let app: any;
  let db: any;

  beforeEach(async () => {
    const harness = await buildApp(transactionsRoutes, '/api/v1/transactions');
    app = harness.app;
    db = harness.db;
  });

  it('creates a transaction mapping amount to amountCents', async () => {
    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/transactions',
      payload: {
        description: 'Supermercado',
        amount: 10050,
        type: 'EXPENSE',
        date: new Date().toISOString(),
        paymentMethod: 'PIX',
      },
    });

    expect(res.statusCode).toBe(201);
    const body = res.json();
    expect(body.description).toBe('Supermercado');
    expect(body.amount).toEqual({ cents: 10050, currency: 'BRL' });

    const rows = db.all(transaction);
    expect(rows).toHaveLength(1);
    expect(rows[0].amountCents).toBe(10050);
    expect(rows[0].userId).toBe(TEST_USER_ID);
    expect(rows[0]).not.toHaveProperty('amount');
  });

  it('rejects a create with an unknown category', async () => {
    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/transactions',
      payload: {
        description: 'Teste',
        amount: 100,
        type: 'EXPENSE',
        date: new Date().toISOString(),
        paymentMethod: 'CASH',
        categoryId: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
      },
    });

    expect(res.statusCode).toBe(400);
  });

  it('updates a transaction mapping amount and date', async () => {
    db.seed(transaction, [{
      id: '99999999-9999-4999-8999-999999999999',
      userId: TEST_USER_ID,
      description: 'Antiga',
      amountCents: 1000,
      type: 'EXPENSE',
      date: new Date(),
      paymentMethod: 'CASH',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const newDate = new Date('2025-01-01T00:00:00.000Z');

    const res = await app.inject({
      method: 'PATCH',
      url: '/api/v1/transactions/99999999-9999-4999-8999-999999999999',
      payload: { description: 'Nova', amount: 2500, date: newDate.toISOString() },
    });

    expect(res.statusCode).toBe(200);
    expect(res.json().amount).toEqual({ cents: 2500, currency: 'BRL' });

    const rows = db.all(transaction);
    expect(rows[0].amountCents).toBe(2500);
    expect(rows[0].description).toBe('Nova');
    expect(rows[0].date).toEqual(newDate);
    expect(rows[0]).not.toHaveProperty('amount');
  });

  it('returns 404 when getting a transaction owned by another user', async () => {
    db.seed(transaction, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
      userId: OTHER_USER_ID,
      description: 'Outra',
      amountCents: 1000,
      type: 'EXPENSE',
      date: new Date(),
      paymentMethod: 'CASH',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({ method: 'GET', url: '/api/v1/transactions/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' });
    expect(res.statusCode).toBe(404);
  });

  it('deletes a transaction', async () => {
    db.seed(transaction, [{
      id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
      userId: TEST_USER_ID,
      description: 'Remover',
      amountCents: 500,
      type: 'EXPENSE',
      date: new Date(),
      paymentMethod: 'PIX',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({ method: 'DELETE', url: '/api/v1/transactions/cccccccc-cccc-4ccc-8ccc-cccccccccccc' });
    expect(res.statusCode).toBe(200);
    expect(db.all(transaction)).toHaveLength(0);
  });

  it('rejects editing a transaction generated by an installment plan', async () => {
    db.seed(transaction, [{
      id: 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',
      userId: TEST_USER_ID,
      description: 'Pagamento parcela 1/10 - Notebook',
      amountCents: 25000,
      type: 'EXPENSE',
      date: new Date(),
      paymentMethod: 'BANK_TRANSFER',
      installmentPlanId: 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'PATCH',
      url: '/api/v1/transactions/dddddddd-dddd-4ddd-8ddd-dddddddddddd',
      payload: { description: 'Alterado' },
    });

    expect(res.statusCode).toBe(409);
  });

  it('rejects an edit with an account not owned by the user', async () => {
    db.seed(transaction, [{
      id: 'ffffffff-ffff-4fff-8fff-ffffffffffff',
      userId: TEST_USER_ID,
      description: 'Sem conta',
      amountCents: 1000,
      type: 'EXPENSE',
      date: new Date(),
      paymentMethod: 'CASH',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'PATCH',
      url: '/api/v1/transactions/ffffffff-ffff-4fff-8fff-ffffffffffff',
      payload: { accountId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' },
    });

    expect(res.statusCode).toBe(400);
  });

  it('creates an installment plan when installmentsCount is provided', async () => {
    db.seed(creditCard, [{
      id: '11111111-1111-4111-8111-111111111111',
      userId: TEST_USER_ID,
      name: 'Visa',
      institution: 'Banco',
      brand: 'VISA',
      last4: '1234',
      limitCents: 100000,
      availableLimitCents: 100000,
      closingDay: 5,
      dueDay: 10,
      status: 'ACTIVE',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/transactions',
      payload: {
        description: 'Notebook',
        amount: 30000,
        type: 'EXPENSE',
        date: new Date().toISOString(),
        paymentMethod: 'CREDIT_CARD',
        cardId: '11111111-1111-4111-8111-111111111111',
        installmentsCount: 3,
      },
    });

    expect(res.statusCode).toBe(201);
    expect(res.json().installments).toHaveLength(3);
    expect(db.all(transaction)).toHaveLength(0);
    expect(db.all(installmentPlan)).toHaveLength(1);
    expect(db.all(installment)).toHaveLength(3);
  });

  it('creates a transaction with people splits', async () => {
    db.seed(person, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaab',
      userId: TEST_USER_ID,
      name: 'Maria',
      type: 'INDIVIDUAL',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/transactions',
      payload: {
        description: 'Jantar',
        amount: 10000,
        type: 'EXPENSE',
        date: new Date().toISOString(),
        paymentMethod: 'PIX',
        splits: [{ personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaab', amountCents: 5000 }],
      },
    });

    expect(res.statusCode).toBe(201);
    expect(db.all(transactionSplit)).toHaveLength(1);
    expect(db.all(transactionSplit)[0].personId).toBe('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaab');
    expect(Number(db.all(transactionSplit)[0].amountCents)).toBe(5000);
  });

  it('rejects a transaction whose splits exceed the amount', async () => {
    db.seed(person, [{
      id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaac',
      userId: TEST_USER_ID,
      name: 'João',
      type: 'INDIVIDUAL',
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);

    const res = await app.inject({
      method: 'POST',
      url: '/api/v1/transactions',
      payload: {
        description: 'Jantar',
        amount: 10000,
        type: 'EXPENSE',
        date: new Date().toISOString(),
        paymentMethod: 'PIX',
        splits: [{ personId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaac', amountCents: 15000 }],
      },
    });

    expect(res.statusCode).toBe(400);
    expect(db.all(transactionSplit)).toHaveLength(0);
  });
});